spring:
  application:
    name: spring-security-custom-auth

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day




